version: '3'
services:

  proxy:
    build:
      context: proxy
      dockerfile: Dockerfile
    depends_on:
      - node
    volumes:
      - ./proxy/envoy-config.yaml:/etc/envoy.yaml
    networks:
      - alastria
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
    restart:
      on-failure

  node:
    build:
      context: validator
      dockerfile: Dockerfile
    command: ["${NODE_TYPE}","${NODE_NAME}"]
    volumes:
      - ${DATA_DIR}:/root/alastria
    networks:
      alastria:
        aliases:
          - node
    restart:
      on-failure
          
networks:
  alastria: